Velocity platform impl
Diruptio/ObsidianCloud pull request #41
Opened 2024-08-06 17:19 UTC by Idiotischer

2024-08-18 15:52 UTC, FabiPunktExe commented
mach gradle spotlessApply

2024-09-01 11:36 UTC, FabiPunktExe requested changes
Bau ein dass die Server in Velocity registriert werden

2024-09-20 09:26 UTC, FusseligerDev commented on platform/paper/src/main/java/de/obsidiancloud/platform/paper/ObsidianCloudPaper.java
> +@SuppressWarnings("unused")
Mach das weg

2024-09-20 09:26 UTC, FusseligerDev commented on node/src/main/java/de/obsidiancloud/node/util/NetworkUtil.java
> +        blockedPorts.remove((Integer) port);
was...

2024-09-20 09:31 UTC, FusseligerDev commented on node/src/main/java/de/obsidiancloud/node/local/template/fabric/FabricTemplate.java
>          int port = NetworkUtil.getFreePort(40000);
Erstell eine Konstante für den start port

2024-09-20 18:49 UTC, FabiPunktExe commented on node/src/main/java/de/obsidiancloud/node/util/NetworkUtil.java
> +        blockedPorts.remove((Integer) port);
Es gibt 2 Funktionen:
List::remove(int index)
List::remove(Object o)
Wenn ich den port als int rein gebe, wird der als index genommen
Wenn ich den port als Integer rein gebe, wird der richtig entfernt

2024-09-20 19:12 UTC, FusseligerDev approved these changes

2024-09-20 19:21 UTC, FabiPunktExe approved these changes

2024-09-20 19:21 UTC, merged